### PR TITLE
Relax zeroize dep

### PR DESCRIPTION
**Pull request by k-bx**
Resolves https://github.com/signalapp/curve25519-dalek/issues/8

### CODE REVIEW

**Comment by k-bx** [comment]
@jrose-signal can we make this happen now?

**Comment by k-bx** [comment]
Sorry, maybe I'm not asking the right question. What should happen next? Should this repo somehow cease to exist? Or update with upstream?

**Comment by jrose-signal** [comment]
We did update with upstream, and the zeroize restriction is removed. However, we still have APIs in this fork that aren't upstream (and don't necessarily make sense to upstream in their current form), so the repo will remain for the time being.

**Comment by k-bx** [comment]
Thanks for the clarification. My goal is to use presage without the zeroize restriction. Right now it's still an issue as of presage's main branch:

```
error: failed to select a version for `zeroize`.
    ... required by package `curve25519-dalek v3.2.1 (https://github.com/signalapp/curve25519-dalek?branch=lizard2#829f52e7)`
    ... which satisfies git dependency `curve25519-dalek` of package `zkgroup v0.9.0 (https://github.com/signalapp/libsignal?tag=v0.28.1#86b2fcc4)`
    ... which satisfies git dependency `zkgroup` of package `libsignal-service v0.1.0 (https://github.com/whisperfish/libsignal-service-rs?rev=8789920#87899201)`
    ... which satisfies git dependency `libsignal-service` of package `libsignal-service-hyper v0.1.0 (https://github.com/whisperfish/libsignal-service-rs?rev=8789920#87899201)`
    ... which satisfies git dependency `libsignal-service-hyper` of package `presage v0.6.0-dev (https://github.com/whisperfish/presage.git#db46e0d8)`
    ... which satisfies git dependency `presage` of package `echo-operator v0.1.0 (/Users/kon/workspace/echo-operator)`
versions that meet the requirements `>=1, <1.4` are: 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0
```

How should this be resolved next, exactly? Really appreciate the help here as I don't fully grasp the right next action.

**Comment by jrose-signal** [comment]
You'll need to be using a later version of libsignal (v0.31 or later), rather than the v0.28.1 that's coming through whisperfish's libsignal-service. Which means using a newer libsignal-service, which might mean using a newer presage.

**Pull request closed without merging**
