### PR TITLE
Rebase lizard2 changes onto 3.0 dalek-cryptography release

### PR DESCRIPTION
**Pull request by jack-signal**
We need this in order to have consistent hash trait versions across poksho and protocol

This is going onto master and leaves lizard2 branch untouched.

Alternately I could just force push on lizard2 branch?

### CODE REVIEW

**Comment by jrose-signal** [comment]
I think either merging or force-pushing to the existing `lizard2` branch makes the most sense. It's good to see that there were no additional changes needed!

**Comment by jack-signal** [comment]
Force pushed onto `lizard2`

**Comment by AsamK** [comment]
Hi, the force push seems to have broken the build of `zkgroup`, which has a git dependency on the lizard2 branch.
https://github.com/signalapp/zkgroup/blob/master/Cargo.lock#L288

Can you either restore the lizard2 branch or update the dependency for zkgroup?

The zkgroup build still works on systems that have built zkgroup previously, because cargo caches the dependency. After deleting the cache `~/.cargo/git`, the build also fails on those systems.

**Comment by jack-signal** [comment]
@AsamK I've pushed a tag 2.0.0-lizard2 which should cause GH to keep the revision that zkgroup references alive.

**Comment by AsamK** [comment]
@jack-signal Thanks! But I still get the same error message ... looks like cargo also checks if the commit is contained in the given branch.
At least the branch name is also included in the Cargo.lock file:
```toml
[[package]]
name = "curve25519-dalek"
version = "2.0.0"
source = "git+https://github.com/signalapp/curve25519-dalek.git?branch=lizard2#477356e017c7cc2aa168f956786b34690870768f"

**Comment by jack-signal** [comment]
Sorry about that. I've force pushed `lizard2` back to it's original state and we've moved the updated version into a new branch.

**Comment by AsamK** [comment]
No worries, thanks for fixing :+1:

**Pull request closed without merging**
